version: "3"
services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: "mongodb_linkapi"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod

  backend:
    image: node:14.15.4
    restart: always
    container_name: backend_link_api
    volumes:
      - .:/backend
      - /node_modules
    ports:
      - 3000:3000
    command: bash -c "cd /backend && node_modules/.bin/nodemon"